name: Automated tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: 19

      - name: Build
        run: mvn verify -DskipTests -Dcheckstyle.skip

  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: 19

      - name: Verify the checkstyle
        run: mvn checkstyle:check

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: 19

      - name: Run the tests
        run: mvn verify -Dcheckstyle.skip